### ISSUE TITLE
Missing scripts?

### ISSUE THREAD

**Issue by TiborUdvari** [molab-itp/p5mirror#1]
Hi,

I was reading the discussions about syncing the p5 editor with git and I stumbled upon your repo. I was wondering how you were handling downloads. It seems to me that there are script that are not included in this repo like `downloads/gen/download.sh` and others that seem to do the heavy lifting, is that the case?

**Comment by jht9629-nyu** [comment]
when you fork this repo and run the script:
bin/mirror.sh --user p5name
the download scripts will be created.

**Comment by leey611** [comment]
in the command, put your p5 editor account name instead of "p5name."

**Comment by TiborUdvari** [comment]
It is working, I just don't understand how, I wanted to check how you did the download script.

**Comment by jht9629-nyu** [comment]
After you run the mirror command you should see a file 
- downloads/gen/download.sh
this contains the scripts to download the sketches as zip files
- downloads/gen/unzip.sh
scripts to unzip the sketches

**Comment by jht9629-nyu** [comment]
nodejs scripts used to create the download scripts
- [p5mirrorLib](https://github.com/molab-itp/p5mirrorLib)
